# To run: conda env create -f environment.yml
name: metcnn
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - cudatoolkit=10.0
  - itk==5.2.0
  - matplotlib==3.3.1
  - numba==0.55.1
  - numpy==1.19.5
  - PyYAML==6.0
  - scikit_image==0.18.3
  - SimpleITK==2.2.1
  - skimage==0.0
  - torch==1.10.2
  - tqdm==4.55.0